name: java-ms-template-ci

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.5
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: publish
        if: github.ref == "master"
        run: |
          docker login docker.pkg.github.com -u mishalshah92 -p ${{ secrets.GITHUB_TOKEN }}
          docker tag java-ms-template_java-ms-template:latest docker.pkg.github.com/zero-templates/java-ms-template/java-ms-template:latest
          docker push docker.pkg.github.com/zero-templates/java-ms-template/java-ms-template:latest